apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-api
        tier: backend
        track: stable
    spec:
      containers:
      - name: web-api
        image: us.gcr.io/<gcp-project>/web-api:0.0.2
        ports:
        - containerPort: 8080
        